[2024-09-30T19:50:07.883+0000] {processor.py:156} INFO - Started process (PID=60) to work on /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:07.883+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/etl_users.py for tasks to queue
[2024-09-30T19:50:07.884+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:07.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:08.985+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:08.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_users.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_users.py", line 17, in <module>
    from Senior_Data_Analyst_Challenge.ingestion_incremental.ingestion_inicial import main
ModuleNotFoundError: No module named 'Senior_Data_Analyst_Challenge'
[2024-09-30T19:50:08.985+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:09.010+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/etl_users.py took 1.132 seconds
[2024-09-30T19:50:41.805+0000] {processor.py:156} INFO - Started process (PID=123) to work on /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:41.807+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/etl_users.py for tasks to queue
[2024-09-30T19:50:41.808+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:41.808+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:44.117+0000] {logging_mixin.py:149} INFO - [2024-09-30T19:50:44.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_users.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_users.py", line 17, in <module>
    from Senior_Data_Analyst_Challenge.ingestion_incremental.ingestion_inicial import main
ModuleNotFoundError: No module named 'Senior_Data_Analyst_Challenge'
[2024-09-30T19:50:44.117+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_users.py
[2024-09-30T19:50:44.168+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/etl_users.py took 2.370 seconds
